spring.application.name=bike-maintenance-adapter

app.repository.bike=memory

app.repository.work-order=memory
app.repository.maintenance-issue=memory

spring.graphql.graphiql.enabled=true

app.seed-data=true

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration,\
org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration,\
org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration,\
org.springframework.boot.data.mongodb.autoconfigure.DataMongoRepositoriesAutoConfiguration